# Generated by Django 5.2.8 on 2025-11-27 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Nome do ícone da sua UI (opcional)', max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurantes/logos/')),
                ('description', models.TextField(blank=True, help_text='Descrição curta do restaurante')),
                ('cuisine_type', models.CharField(choices=[('brasileira', 'Brasileira'), ('japonesa', 'Japonesa'), ('italiana', 'Italiana'), ('árabe', 'Árabe'), ('vegana', 'Vegana'), ('cafeteria', 'Cafeteria'), ('lanches', 'Lanches'), ('internacional', 'Internacional'), ('outros', 'Outros')], default='outros', max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('building', models.CharField(blank=True, help_text='Ex: Frings, Pilotis, etc.', max_length=80)),
                ('opening_hours', models.CharField(blank=True, help_text='Ex: Seg–Sex 8h–22h', max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('instagram', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('price_level', models.PositiveSmallIntegerField(default=1, help_text='1–5 (quanto mais alto, mais caro)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pratos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='puceats.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='puceats.restaurant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
